# Generated by Django 3.2.9 on 2021-11-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='male', max_length=9)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
